### ISSUE TITLE
Refactor issues #2 and #11

### ISSUE THREAD

**Issue by mpericay** [oscarfonts/besobs#14]

**Comment by mpericay** [comment]
http://stackoverflow.com/questions/20651020/routes-chaining-in-express

**Comment by oscarfonts** [comment]
Yes, in fact both our cors and authentication modules are using the referred route chaining, see:

app.use('/api', cors);
app.use('/api', authenticate);
app.use('/api', cartodb_api);

And if we go into them:

router.use(function (req, res, next) {
    // Do cors or auth things, then pass to the next function:
   next();
}
