### ISSUE TITLE
Auth popup shows if failed login but doesn't work

### ISSUE THREAD

**Issue by mpericay** [oscarfonts/besobs#16]
If you introduce correct credentials a second time, it's useless

**Comment by mpericay** [comment]
2 opcions: 
http://stackoverflow.com/questions/9859627/how-to-prevent-browser-to-invoke-basic-auth-popup-and-handle-401-error-using-jqu

Si es canvia el header, per fer-ho en servidor:
http://stackoverflow.com/questions/24106316/expressjs-change-header-before-passportjs-response

**Comment by mpericay** [comment]
A l'ICUB els headers no estan canviats ... pq funciona?
https://github.com/oscarfonts/icub-mon/blob/master/api/utils/auth.py
Es pot veure desplegat?

**Comment by oscarfonts** [comment]
Me la miro jo

**Comment by oscarfonts** [comment]
Solucionat manipulant el header "WWW-Authenticate", però només per a les crides de tipus AJAX.
Per a crides no-ajax, es manté el comportament per defecte.
També es manté l'ús del codi HTTP 401 Unauthorized en tots els casos, que és més correcte.
