### ISSUE TITLE
[Client] Pujar imatge via API

### ISSUE THREAD

**Issue by oscarfonts** [oscarfonts/besobs#2]
flickr?

**Comment by mpericay** [comment]
https://github.com/Pomax/node-flickrapi

https://github.com/blueimp/jQuery-File-Upload/wiki/Setup

https://github.com/crapthings/blueimp-file-upload-node/blob/master/server.js

**Comment by oscarfonts** [comment]
Intentaria pujar-la d'una sola tacada, un POST que contingués, alhora, les dades GeoJSON i la foto. Això es pot fer amb formularis multipart:
http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax
http://stackoverflow.com/questions/9081079/rest-http-post-multipart-with-json
http://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean
