### ISSUE TITLE
Fer que es vegin les imatges al mapa de CartoDB

### ISSUE THREAD

**Issue by oscarfonts** [oscarfonts/besobs#21]
Per exemple mostrar-la a la capçalera de l'info, que és una cosa que el mateix wizard de CartoDB permetia fer (si no ho han canviat).

Abans, però, cal desplegar la nova versió de l'aplicació a una URL pública.

**Comment by mpericay** [comment]
Aixo esta fet crec. Només q despleguis funcionarà.
El dia 09/12/2015 12:53, "Oscar Fonts" notifications@github.com va
escriure:

**Comment by oscarfonts** [comment]
Martí, les URLs de les imatges fins ara apuntaven a "localhost"; no era possible veure-les. He netejat la taula de dades, i he pujat una mostra al server.

Aquí està el form públic i el mapa resultant:
http://demo.geomati.co/besobs/
http://bit.ly/1YgvFdO
