### ISSUE TITLE
Definir i gestionar els usuaris

### ISSUE THREAD

**Issue by oscarfonts** [oscarfonts/besobs#30]
Fer CRUD per gestionar usuaris.

És un cas molt comú, per tant, mirar si es pot integrar alguna solució existent que també faci servir passport. Per exemple, http://jedireza.github.io/drywall/

En cas que la integració de solucions existents no sigui fàcil, aquí va una proposta de disseny d'una solució pròpia (no és tan complicat com sembla):

A la BDD d'usuaris, afegir una columna booleana `isAdmin`, que per defecte serà `false`. Canviar el codi existent per poder indicar aquest flag en crear o validar un usuari.

Al mòdul "auth", a més de les rutes `/login` i `/logout` existents, afegir l'API necessària per gestionar usuaris:
- ruta `/users.json` que:
  - fent un `GET` recuperi una llista de tots els usuaris existents (id, nom, isAdmin).
  - fent un `POST` es pugui donar d'alta un nou usuari (enviar nom, password, isAdmin; recuperar id, nom i isAdmin, o error).
- ruta `/users/{id}.json` que:
  - fent `PUT` es pugui editar l'usuari (enviar nom nou, password antic i password nou, i isAdmin; recuperar id, nom i isAdmin, o error).
  - fent `DELETE` es pugui eliminar l'usuari, excepte si resulta ser l'usuari amb el que estem logats (ens assegurem de mantenir al menys un admin actiu).

A aquestes rutes només hi podran accedir els usuaris `isAdmin == true`; el content-type serà `text/json`.

Molaria separar-ho en dos fitxers: el que es baralla amb la BDD i el que es baralla amb les URLs à la REST. Semblant al model i controlador proposat aquí: https://uno-de-piera.com/sqlite3-con-node-js-y-express/

Per últim, la vista: Crear pàgina HTML/JS per gestionar els usuaris, què mostrarà la llista d'usuaris amb enllaços a "editar" i "esborrar" per a cadascun, i un botó de "nou usuari".
- Editar obre un formulari per canviar nom, password i status d'administrador.
- Esborrar demana confirmació mitjançant diàleg modal.
- Crear obre un altre formulari.
- En finalitzar cada operació, s'actualitza la llista d'usuaris.

Aquesta pàgina podria mapejar-se a la URL `/users`, o `/admin`, i ser accessible només si estem logats com a usuari administrador.

La pàgina principal del projecte (formulari) haurà d'incloure un enllaç a la d'administració d'usuaris quan l'usuari sigui `isAdmin`.

**Comment by mpericay** [comment]
Drywall sembla molt massa feixuc per a implementar sencer, però potser només una API (https://github.com/jedireza/frame/) seria possible. Això si, implica canviar SQLite per MongoDB, que potser molesta una mica?
Hi ha moltes més funcionalitats del que necessitem: https://hapiframe.herokuapp.com/docs

**Comment by mpericay** [comment]
https://www.phpliteadmin.org/

**Comment by oscarfonts** [comment]
Jamás!

**Comment by mpericay** [comment]
Jajaja! PHP or die!
Sorry però no hi ha cap nodeLiteAdmin ... de les eines web, aquesta sembla l'única sèria. Si no, a fer-la nosaltres.

**Comment by oscarfonts** [comment]
Incloure una altra tecnologia de servidor implica un desplegament més complex i més costos de manteniment, no crec que valgui la pena. Ja en faig jo l'implementació.

**Comment by oscarfonts** [comment]
Implementat a pèl:
https://github.com/oscarfonts/besobs/commit/63d9e0cf16c4d0df23adc56a4ea334b6dbdaf449

Faltarà:
- Incloure la propietat "isAdmin".
- Enllaçar des del formulari principal.
- Bloquejar l'esborrat del darrer admin (backend) i/o de l'usuari logat en aquest moment (frontend).
