### ISSUE TITLE
Fer una vista de mapa basada en CartoDB

### ISSUE THREAD

**Issue by oscarfonts** [oscarfonts/besobs#33]
Amb coses que siguin maques i fàcils de fer: Clustering, filtrat/cerca...

PS. Assigno a @mpericay a canvi de la de gestió d'usuaris. Serà més eficient.

**Comment by mpericay** [comment]
We use directly CartoDBEditor: https://consorcibesos.cartodb.com/viz/1328f008-e7a2-11e5-a2c6-0ecfd53eb7d3/public_map
