### ISSUE TITLE
[Client] Enviar dades formulari via API, amb autenticació

### ISSUE THREAD

**Issue by mpericay** [oscarfonts/besobs#8]

**Comment by mpericay** [comment]
For serializing photo
http://portfolio.planetjon.ca/2014/01/26/submit-file-input-via-ajax-jquery-easy-way/

**Comment by oscarfonts** [comment]
Subtasques:
- Definir la colla de properties que tindrà una observació, serialitzada en format GeoJSON.
- Crear la taula corresponent a CartoDB.
- Comprovar que realment funciona i que les dades acaben a CartoDB.

**Comment by oscarfonts** [comment]
Format proposat del POST (que no PUT):

```
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "geometry":{
            "type":"Point",
            "coordinates":[
               2.22319,
               41.42374
            ]
         },
         "properties":{
            "username":"jcalafi",
            "date":"2015-11-19",
            "class":"una_clase",
            "species":"una_especie",
            "image":"TODO",
            "notes":"bla bla"
         }
      }
   ]
}
```

**Comment by oscarfonts** [comment]
Ok, dades ja arriben a CartoDB.

Queda:
a) millorar la gestió d'errors (ensenyar missatge quan alguna cosa falla),
b) comprovar que hi ha informats certs camps obligatoris (location, date, i class or species).

Reassigno.
